image:https://img.shields.io/badge/maven%20central-v3.0.1-blue.svg["Maven Central",link="https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22quickfixj-spring-boot-starter%22"]
image:https://img.shields.io/hexpm/l/plug.svg["Apache 2",link="http://www.apache.org/licenses/LICENSE-2.0"]



= Influx-orm-spring-boot-starter（For Spring Boot 3.x）
This project is an Influx ORM framework based on https://spring.io/projects/spring-boot/[Spring Boot Starter]. It separates query statements from business, simplifies the development process, improves development efficiency, reduces the workload of manually processing SQL, and only requires adding interfaces and statements on methods.

== Requirements
- Java 17+
- Spring Boot 3.x.x


== Installation
To use Influx-orm-spring-boot-starter, you need to add the Influx orm Spring Boot Starter dependency to your project.
[source,xml]
----
<dependency>
    <groupId>io.github.skyxiaosw</groupId>
    <artifactId>influx-orm-spring-boot-starter</artifactId>
    <version>2.0</version>
</dependency>
----

== Configuration
Add the following configuration to your properties file.

[source,properties]
----
influx.enable=true
influx.url=http://127.0.0.1:8086?readTimeout=10s&connectTimeout=5s&logLevel=BODY&writeTimeout=10s
influx.bucket=your-bucket
influx.token=your-token
influx.org=your-org
----

[source,yml]
----
influx:
  bucket: your-bucket
  enable: true
  org: your-org
  token: your-token
  url: http://127.0.0.1:8086?readTimeout=10s&connectTimeout=5s&logLevel=BODY&writeTimeout=10s
----

== Usage

Add the following annotation @EnableInfluxMappers to your main class.
[source,java]
----

@SpringBootApplication
@EnableInfluxMappers
public class AppApplication {
    public static void main(String[] args) {
        SpringApplication.run(AppApplication.class);
    }
}
----

=== Influx orm Spring Boot Starter mapper
Influx orm Spring Boot Starter mapper is a component that maps SQL statements to Java interfaces.

[source,java]
----
import com.data.source.orm.influx.annotation.InfluxMapper;
import com.data.source.orm.influx.annotation.ParamName;
import com.data.source.orm.influx.annotation.Select;

@InfluxMapper
public interface TestMapper {

    @Select(
        """
            from(bucket: "#{bucket}")
            |> range(start:#{start},stop:#{stop})
            |> filter(fn: (r) => r._measurement == "your_measurement" )
            |> filter(fn: (r) => r.name == "#{name}" and r.id == "#{id}")
            |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")
            |> sort(columns:["_time"], desc: true)
        """
    )
    List<UserEntity> queryUser(UserRequest userRequest);

}
----


the usage is as follows:
[source,java]
----

    @Autowired(required = false)
    private TestMapper testMapper;

----


== License

Spring Boot is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].